# Generated by ./bin/ip-to-dns.sh
resource "aws_route53_record" "training-vm-us-0" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-0.us.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.170.130"]
}

resource "aws_route53_record" "training-vm-us-1" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-1.us.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.171.173"]
}

resource "aws_route53_record" "training-vm-us-2" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-2.us.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.156.169"]
}

resource "aws_route53_record" "training-vm-us-3" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-3.us.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.171.202"]
}

