# Generated by ./bin/ip-to-dns.sh
resource "aws_route53_record" "training-vm-oz-0" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-0.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.113"]
}

resource "aws_route53_record" "training-vm-oz-1" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-1.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.55"]
}

resource "aws_route53_record" "training-vm-oz-2" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-2.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.84.180"]
}

resource "aws_route53_record" "training-vm-oz-3" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-3.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.30"]
}

resource "aws_route53_record" "training-vm-oz-4" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-4.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.20"]
}

resource "aws_route53_record" "training-vm-oz-5" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-5.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.84.30"]
}

resource "aws_route53_record" "training-vm-oz-6" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-6.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.52"]
}

resource "aws_route53_record" "training-vm-oz-7" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-7.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.19"]
}

resource "aws_route53_record" "training-vm-oz-8" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-8.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.112"]
}

resource "aws_route53_record" "training-vm-oz-9" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-9.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.81"]
}

resource "aws_route53_record" "training-vm-oz-10" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-10.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.217"]
}

resource "aws_route53_record" "training-vm-oz-11" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-11.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.84.219"]
}

resource "aws_route53_record" "training-vm-oz-12" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-12.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["203.101.230.4"]
}

resource "aws_route53_record" "training-vm-oz-13" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-13.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.84.63"]
}

resource "aws_route53_record" "training-vm-oz-14" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-14.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.83"]
}

resource "aws_route53_record" "training-vm-oz-15" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-15.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.50"]
}

resource "aws_route53_record" "training-vm-oz-16" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-16.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.84.60"]
}

resource "aws_route53_record" "training-vm-oz-17" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-17.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.177"]
}

resource "aws_route53_record" "training-vm-oz-18" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-18.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["203.101.227.62"]
}

resource "aws_route53_record" "training-vm-oz-19" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "gat-19.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.98"]
}

resource "aws_route53_record" "training-vm-oz-gxit-wildcard" {
  zone_id = "${aws_route53_zone.training-gxp-eu.zone_id}"
  name    = "*.interactivetoolentrypoint.interactivetool.gat-${count.index}.oz.training.galaxyproject.eu"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-${count.index}.oz.training.galaxyproject.eu"]
  count   = "20"
}
